# Parameters for PyAnimats.
---
# The seed for the random number generators.
SEED: 0
# The number of generations to simulate.
NGEN: 10
# The fitness function to use. For a list of available functions, use
# `--list-fitness-funcs`.
FITNESS_FUNCTION: 'nat'
# The number of individuals in the population at every generation.
POPSIZE: 100
# Whether to randomly rearrange the animat's game world on every trial.
SCRAMBLE_WORLD: False
# Individual nucleotide mutation probability.
MUTATION_PROB: 0.005
# Probability that a section of the genome is duplicated.
DUPLICATION_PROB: 0.05
# Probability that a section of the genome is deleted.
DELETION_PROB: 0.02
# No duplication will occur if genome is this long or longer.
MAX_GENOME_LENGTH: 10000
# No deletion will occur if genome is this long or longer.
MIN_GENOME_LENGTH: 1000
# The duplicated/deleted section will be at least this long.
MIN_DUP_DEL_WIDTH: 15
# The duplicated/deleted section will be shorter than this.
MAX_DUP_DEL_WIDTH: 511
# Base used in fitness functions to make fitness increases exponential.
FITNESS_BASE: 1.02
# The number of start codons to insert into the initial genome.
INIT_START_CODONS: 0
